name = "Wynncraft Pack"
author = "TacoMonkey"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e620a8e3b5336fe1115b71aad4c8613c5b37c41b7bf4c85fe776a188e5d98ed"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
