name = "Wynncraft Pack"
author = "TacoMonkey"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d11b7c618b3758a1b622aaa2290a2848a71252ae116f863b359aebab2c0355c6"

[versions]
fabric = "0.14.19"
minecraft = "1.19.3"
