name = "Wynncraft Pack"
author = "TacoMonkey"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a9261fda40639d20792a07e2b6c6286364174b68e70c1d8556439e55a74f645"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
