name = "Wynncraft Pack"
author = "TacoMonkey"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fb3cccc35a5c0872e0fcc225d23458b2e113e9d322d7212badf66b5575276b2"

[versions]
fabric = "0.14.19"
minecraft = "1.19.3"
