name = "Wynncraft Pack"
author = "TacoMonkey"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af701ab974189e347756c339e43538b6a0080faeb44ccdffbe70ebb4390be24e"

[versions]
fabric = "0.14.19"
minecraft = "1.19.3"
