# This is a basic workflow to help you get started with Actions

name: Publish to Modrinth

# Controls when the workflow will run
on:
  release:
    types: [published]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup Go environment
        uses: actions/setup-go@v4.0.0
        
      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest
      
      - name: Export modpack
        run: packwiz mr export
      
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: yZS0449h
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          
          github-token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          
          files-primary: Wynncraft Pack-*.mrpack
          loaders: |
            fabric
          
